Repository elastic/hey-apm, pull requests merged in 2019-08, with the labels that each got.

#125 ci: benchmark stage in the jenkins pipeline
  .ci/jobs/apm-hey-test-mbp.yml
  Jenkinsfile
  README.md
  docker-compose.yml
  docker/Dockerfile-bench
  scripts/jenkins/run-bench-in-docker.sh
Labels: [zube]: In Review, automation, benchmarking, ci

#128 ci: uses another ES benchmark cluster
  Jenkinsfile
Labels: automation, benchmarking, ci

#130 fix: pipeline is not anymore a MBP
  .ci/scheduled-benchmark.groovy
Labels: automation, ci

#131 ci(jenkins): GitHub notifications are not required
  .ci/scheduled-benchmark.groovy
Labels: automation, bug

#134 ensure that default input doesn't have missing values and add docs
  benchmark/benchmark.go
  main.go
  main_test.go
  models/input.go
Labels: [zube]: In Review

#138 [apm-ci] run CI everyday
  .ci/jobs/apm-hey-test-benchmark.yml
  .ci/scheduled-benchmark.groovy
Labels: automation, ci
